# torch `nn.Embedding`

## 사전학습된 임베딩을 사용하지 않는 경우

In [1]:
# 감성 분석 샘플 데이터
sentences = [
    'nice great best amazing',
    'stop lies',
    'pitiful nerd',
    'excellent work',
    'supreme quality',
    'bad',
    'highly respectable'
]
labels = [1, 0, 0, 1, 1, 0, 1]

In [2]:
# 토큰화
from nltk.tokenize import word_tokenize

tokenized_sentences = [word_tokenize(sent) for sent in sentences]
tokenized_sentences

[['nice', 'great', 'best', 'amazing'],
 ['stop', 'lies'],
 ['pitiful', 'nerd'],
 ['excellent', 'work'],
 ['supreme', 'quality'],
 ['bad'],
 ['highly', 'respectable']]

In [4]:
# 단어 사전/정수 인코딩
from collections import Counter

tokens = [token for sent in tokenized_sentences for token in sent]
word_counts = Counter(tokens)
print(word_counts)

word_to_index = {word:index+2 for index,word in enumerate(tokens)}
word_to_index['<PAD>'] = 0
word_to_index['<UNK>'] = 1
word_to_index = dict(sorted(word_to_index.items(),key=lambda x:x[1]))
print(word_to_index)

vocab_size = len(word_to_index)
vocab_size

Counter({'nice': 1, 'great': 1, 'best': 1, 'amazing': 1, 'stop': 1, 'lies': 1, 'pitiful': 1, 'nerd': 1, 'excellent': 1, 'work': 1, 'supreme': 1, 'quality': 1, 'bad': 1, 'highly': 1, 'respectable': 1})
{'<PAD>': 0, '<UNK>': 1, 'nice': 2, 'great': 3, 'best': 4, 'amazing': 5, 'stop': 6, 'lies': 7, 'pitiful': 8, 'nerd': 9, 'excellent': 10, 'work': 11, 'supreme': 12, 'quality': 13, 'bad': 14, 'highly': 15, 'respectable': 16}

17

In [7]:
def texts_to_sequences(sentences,word_to_index):
    sequences = []

    for sent in sentences:
        sequence = []
        for token in sent:
            if token in word_to_index:
                sequence.append(word_to_index[token])
            else:
                sequence.append(word_to_index['<UNK>'])

        sequences.append(sequence)
    return sequences

sequences = texts_to_sequences(tokenized_sentences,word_to_index)
sequences

[[2, 3, 4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14], [15, 16]]

In [8]:
# 패딩
import numpy as np

def pad_squences(sequences,maxlen):
    padded_squences = np.zeros([len(sequences),maxlen],dtype=int)
    for index, seq in enumerate(sequences):
        padded_squences[index, : len(seq)] = seq[:maxlen]
    return padded_squences

padded_squences = pad_squences(sequences,maxlen=4)
padded_squences

array([[ 2,  3,  4,  5],
       [ 6,  7,  0,  0],
       [ 8,  9,  0,  0],
       [10, 11,  0,  0],
       [12, 13,  0,  0],
       [14,  0,  0,  0],
       [15, 16,  0,  0]])

In [9]:
# 모델 생성
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader,TensorDataset

class SimpleNet(nn.Module):
    def __init__(self,vocab_size,embedding_dim,hidden_size):
        super().__init__()
        self.embadding = nn.Embedding(
            num_embeddings=vocab_size,
            embedding_dim=embedding_dim,
            padding_idx=0           # 패딩 벡터는 학습하지 않음
        )
        self.rnn = nn.RNN(embedding_dim,hidden_size,batch_first=True)
        self.out = nn.Linear(hidden_size,1)

    def forward(self,x):
        embbedded = self.embadding(x)
        _,h_n = self.rnn(embbedded)
        out = self.out(h_n.squeeze(0))
        return out

embedding_dim=100
model = SimpleNet(vocab_size,embedding_dim,hidden_size=8)
model

SimpleNet(
  (embadding): Embedding(17, 100, padding_idx=0)
  (rnn): RNN(100, 8, batch_first=True)
  (out): Linear(in_features=8, out_features=1, bias=True)
)

In [10]:
import pandas as pd

# 학습 전 임베딩 벡터
wv = model.embadding.weight.data
print(wv.shape)

# 특정 단어 벡터
vocab = word_to_index.keys()
pd.DataFrame(wv,index=vocab)

torch.Size([17, 100])

                   0         1         2   ...        97        98        99
<PAD>        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
<UNK>       -1.581655  0.027303  0.472419  ... -0.459283 -1.476712  0.989287
nice         1.102290  1.057616  1.981297  ...  0.276331 -1.208762 -1.469257
great       -1.117050 -0.378348 -0.194045  ... -0.897019 -0.614904 -1.344293
best         0.220408 -0.766197 -0.715310  ...  0.287397 -0.873428  0.171039
amazing      0.261244  0.253975 -0.888293  ...  2.438191  0.455433 -0.397102
stop        -1.164891 -0.768962 -1.581568  ... -1.746292 -1.902289 -1.430531
lies         1.403513 -0.373321 -0.216625  ... -0.733475  0.402074  0.087208
pitiful     -1.058131  0.394002 -0.460706  ...  0.685517 -1.180997  1.654375
nerd        -0.871719  2.488099 -0.947100  ...  0.065608  0.748189 -1.833785
excellent    0.760602 -0.330356  0.431469  ...  1.200655  1.185898 -0.634817
work         1.429741  0.337474  0.821141  ...  0.054068 -1.192084  0.060541
supreme      1.359746 -0.823307 -0.439988  ...  0.152980 -0.168749 -0.061023
quality     -1.270498  1.388168 -1.265311  ... -1.383580 -0.492513  0.453752
bad          0.706422  0.075084  0.573460  ...  0.728034  1.547543 -0.508765
highly      -1.144761 -0.703440 -0.649567  ...  0.577492  0.472567 -0.044189
respectable -0.045263 -0.116789  1.006412  ...  0.345526  2.669582  1.074273

[17 rows x 100 columns]

In [ ]:
# 모델 학습
X = torch.tensor(padded_squences,dtype=torch.long)              # (batch_size,seq_len)
y= torch.tensor(labels,dtype=torch.float).unsqueeze(1)          # (batch_size,1)

print(f'{X.shape}, {y.shape}')

dataset = TensorDataset(X,y)
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(),lr=0.005)

torch.Size([7, 4]), torch.Size([7, 1])

In [ ]:
for epoch in range(20):
    epoch_loss = 0
    for x_batch,y_batch in dataloader:
        optimizer.zero_grad()
        output = model(x_batch)
        loss = criterion(output,y_batch)
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()

    print(f'epoch {epoch+1} : Loss : {epoch_loss / len(dataloader)}')

epoch 1 : Loss : 0.7139550000429153
epoch 2 : Loss : 0.6345522105693817
epoch 3 : Loss : 0.659809410572052
epoch 4 : Loss : 0.6475090235471725
epoch 5 : Loss : 0.6304106563329697
epoch 6 : Loss : 0.5927340164780617
epoch 7 : Loss : 0.5614373832941055
epoch 8 : Loss : 0.5324572026729584
epoch 9 : Loss : 0.4734615609049797
epoch 10 : Loss : 0.456064835190773
epoch 11 : Loss : 0.41850627958774567
epoch 12 : Loss : 0.3739061877131462
epoch 13 : Loss : 0.33644118905067444
epoch 14 : Loss : 0.31425290554761887
epoch 15 : Loss : 0.2548166438937187
epoch 16 : Loss : 0.23968198150396347
epoch 17 : Loss : 0.20070943236351013
epoch 18 : Loss : 0.17549549043178558
epoch 19 : Loss : 0.15937422960996628
epoch 20 : Loss : 0.13613549806177616
epoch 21 : Loss : 0.12280835025012493
epoch 22 : Loss : 0.10608835145831108
epoch 23 : Loss : 0.09482093900442123
epoch 24 : Loss : 0.08543062582612038
epoch 25 : Loss : 0.07652867212891579
epoch 26 : Loss : 0.06947429291903973
epoch 27 : Loss : 0.06384665798395872
epoch 28 : Loss : 0.05882067885249853
epoch 29 : Loss : 0.054378461092710495
epoch 30 : Loss : 0.050562797114253044

In [ ]:
# 평가/ 예측
model.eval()
with torch.no_grad():
    output = model(X)
    prob = torch.sigmoid(output)
    pred = (prob >= 0.5).int()

print(labels)
print(pred.squeeze().detach().numpy())

[1, 0, 0, 1, 1, 0, 1]
[1 0 0 1 1 0 1]

In [15]:
# 학습 후 임베딩 벡터
wv = model.embadding.weight.data
print(wv.shape)

# 특정 단어 벡터
vocab = word_to_index.keys()
pd.DataFrame(wv,index=vocab)

torch.Size([17, 100])

                   0         1         2   ...        97        98        99
<PAD>        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
<UNK>       -1.581655  0.027303  0.472419  ... -0.459283 -1.476712  0.989287
nice         1.084368  1.118087  2.044694  ...  0.222110 -1.216451 -1.451392
great       -1.092873 -0.342970 -0.157977  ... -0.908768 -0.581416 -1.371029
best         0.252093 -0.804658 -0.753133  ...  0.315431 -0.858428  0.207899
amazing      0.226518  0.288691 -0.944361  ...  2.543322  0.463679 -0.509166
stop        -1.076872 -0.923699 -1.709428  ... -1.616593 -1.898733 -1.517070
lies         1.454498 -0.382640 -0.287003  ... -0.679544  0.513254  0.125024
pitiful     -0.973451  0.311458 -0.580048  ...  0.756797 -1.164609  1.624440
nerd        -0.777319  2.539623 -0.949452  ...  0.098612  0.869192 -1.798244
excellent    0.735700 -0.330516  0.426570  ...  1.098574  1.105843 -0.651587
work         1.317102  0.293920  0.851874  ...  0.068047 -1.302576 -0.000290
supreme      1.372771 -0.730727 -0.395084  ...  0.097213 -0.023127 -0.122689
quality     -1.308906  1.389130 -1.157499  ... -1.408885 -0.557447  0.420060
bad          0.721171  0.081101  0.444530  ...  0.863613  1.598106 -0.631472
highly      -1.186552 -0.593469 -0.568041  ...  0.482339  0.523153 -0.078772
respectable -0.081056 -0.241524  1.105338  ...  0.251670  2.572027  1.026616

[17 rows x 100 columns]

## 사전학습된 임베딩을 사용하는 경우

https://code.google.com/archive/p/word2vec/

In [17]:
# 사전 학습된 임베딩 로드
from gensim.models import KeyedVectors

model_wv = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin',binary=True)
model_wv.vectors.shape

(3000000, 300)

In [20]:
print(model_wv.most_similar('man',topn=5))
print(model_wv.most_similar('woman',topn=5))
print(model_wv.most_similar('king',topn=5))
print(model_wv.most_similar('queen',topn=5))

[('woman', 0.7664012908935547), ('boy', 0.6824871301651001), ('teenager', 0.6586930155754089), ('teenage_girl', 0.6147903203964233), ('girl', 0.5921714305877686)]
[('man', 0.7664012908935547), ('girl', 0.7494640946388245), ('teenage_girl', 0.7336829304695129), ('teenager', 0.6317085027694702), ('lady', 0.6288785934448242)]
[('kings', 0.7138045430183411), ('queen', 0.6510956883430481), ('monarch', 0.6413194537162781), ('crown_prince', 0.6204220056533813), ('prince', 0.6159993410110474)]
[('queens', 0.739944338798523), ('princess', 0.7070532441139221), ('king', 0.6510956883430481), ('monarch', 0.6383602023124695), ('very_pampered_McElhatton', 0.6357026696205139)]

In [22]:
print(model_wv.most_similar(positive=['king','woman'],negative=['man'],topn=5))
print(model_wv.most_similar(positive=['paris','italy'],negative=['france'],topn=5))

[('queen', 0.7118193507194519), ('monarch', 0.6189674139022827), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321839332581)]
[('lohan', 0.5069674849510193), ('madrid', 0.481842964887619), ('heidi', 0.4799900949001312), ('real_madrid', 0.4753323495388031), ('florence', 0.4682057499885559)]

In [25]:
# 모델의 Embedding layer에 초기화 할 embedding_matrix
print(len(word_to_index))       # (17,300) 크기의 embedding_matrix 생성

embedding_matrix = np.zeros((len(word_to_index),model_wv.vectors.shape[1]))
print(embedding_matrix.shape)

17
(17, 300)

In [26]:
def get_word_embedding(word):
    if word in model_wv:
        return model_wv[word]
    else:
        return None

for word,index in word_to_index.items():
    if index >=2:
        emb = get_word_embedding(word)
        if emb is not None:
            embedding_matrix[index] = emb

In [27]:
pd.DataFrame(embedding_matrix,index=word_to_index.keys())

                  0         1         2    ...       297       298       299
<PAD>        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
<UNK>        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
nice         0.158203  0.105957 -0.189453  ... -0.267578  0.008362 -0.213867
great        0.071777  0.208008 -0.028442  ... -0.167969 -0.020874 -0.142578
best        -0.126953  0.021973  0.287109  ... -0.101562 -0.090332  0.088379
amazing      0.073730  0.004059 -0.135742  ... -0.141602 -0.150391 -0.137695
stop        -0.057861  0.013184  0.115234  ...  0.086426  0.029907  0.007812
lies         0.149414 -0.012817  0.328125  ... -0.105469  0.149414  0.157227
pitiful      0.269531  0.253906 -0.020996  ... -0.072266 -0.094238  0.028809
nerd         0.265625 -0.207031 -0.026611  ...  0.124023 -0.030273  0.082031
excellent   -0.212891 -0.004303 -0.180664  ... -0.129883 -0.215820  0.012268
work        -0.075684  0.033691 -0.064941  ...  0.012024  0.135742 -0.091309
supreme      0.173828  0.172852  0.112793  ... -0.164062 -0.127930  0.097656
quality     -0.259766  0.271484  0.119629  ... -0.179688  0.000706 -0.014099
bad          0.062988  0.124512  0.113281  ... -0.063477  0.114746  0.031006
highly       0.050781 -0.227539 -0.130859  ... -0.056641  0.102539  0.074707
respectable  0.150391  0.285156 -0.023193  ... -0.200195 -0.112305  0.103027

[17 rows x 300 columns]

In [28]:
# 모델 생성
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader,TensorDataset

class SimpleNet(nn.Module):
    def __init__(self,vocab_size,embedding_dim,embedding_matrix,hidden_size):
        super().__init__()
        self.embadding = nn.Embedding(
            num_embeddings=vocab_size,
            embedding_dim=embedding_dim,
            padding_idx=0           # 패딩 벡터는 학습하지 않음
        )
        # 사전 학습된 임베딩 벡터로 초기화
        self.embadding.weight = nn.Parameter(torch.tensor(embedding_matrix,dtype=torch.float))
        # 사전 학습된 임베딩 벡터는 학습에 사용하지 않음
        self.embadding.weight.requires_grad = False

        self.rnn = nn.RNN(embedding_dim,hidden_size,batch_first=True)
        self.out = nn.Linear(hidden_size,1)

    def forward(self,x):
        embbedded = self.embadding(x)
        _,h_n = self.rnn(embbedded)
        out = self.out(h_n.squeeze(0))
        return out

embedding_dim=model_wv.vectors.shape[1]
model = SimpleNet(vocab_size,embedding_dim,embedding_matrix,hidden_size=8)
model

SimpleNet(
  (embadding): Embedding(17, 300, padding_idx=0)
  (rnn): RNN(300, 8, batch_first=True)
  (out): Linear(in_features=8, out_features=1, bias=True)
)

In [29]:
# 모델 학습
X = torch.tensor(padded_squences,dtype=torch.long)              # (batch_size,seq_len)
y= torch.tensor(labels,dtype=torch.float).unsqueeze(1)          # (batch_size,1)

print(f'{X.shape}, {y.shape}')

dataset = TensorDataset(X,y)
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(),lr=0.005)

torch.Size([7, 4]), torch.Size([7, 1])

In [30]:
for epoch in range(20):
    epoch_loss = 0
    for x_batch,y_batch in dataloader:
        optimizer.zero_grad()
        output = model(x_batch)
        loss = criterion(output,y_batch)
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()

    print(f'epoch {epoch+1} : Loss : {epoch_loss / len(dataloader)}')

epoch 1 : Loss : 0.6889089047908783
epoch 2 : Loss : 0.6427295804023743
epoch 3 : Loss : 0.6122049540281296
epoch 4 : Loss : 0.5217395722866058
epoch 5 : Loss : 0.5076186954975128
epoch 6 : Loss : 0.47869356721639633
epoch 7 : Loss : 0.4281734451651573
epoch 8 : Loss : 0.3724142014980316
epoch 9 : Loss : 0.32294514775276184
epoch 10 : Loss : 0.27368783578276634
epoch 11 : Loss : 0.22431736439466476
epoch 12 : Loss : 0.18332578241825104
epoch 13 : Loss : 0.1529909111559391
epoch 14 : Loss : 0.12731528282165527
epoch 15 : Loss : 0.10853824950754642
epoch 16 : Loss : 0.09286828152835369
epoch 17 : Loss : 0.08066901378333569
epoch 18 : Loss : 0.06966807506978512
epoch 19 : Loss : 0.0618293983861804
epoch 20 : Loss : 0.05580116808414459

In [31]:
# 평가/ 예측
model.eval()
with torch.no_grad():
    output = model(X)
    prob = torch.sigmoid(output)
    pred = (prob >= 0.5).int()

print(labels)
print(pred.squeeze().detach().numpy())

[1, 0, 0, 1, 1, 0, 1]
[1 0 0 1 1 0 1]